### ISSUE TITLE
Stuck on "Debug started on port 4000, waiting on the client to connect..."

### ISSUE THREAD

**Issue by mickeypearce** [zerabba/vscode-plsql-debug#1] opened 2020-04-02 08:16 UTC
I'd really like to try your extension, but I get stuck on "Debug started on port 4000, waiting on the client to connect...". Could you please help me on how to proceed?

I have Java JDK installed, debuging with SQL Developer which also uses JDWP works. I also tried different ports with no success.

**Comment by zerabba** [comment] 2020-04-02 08:37
Hi,

What's happening on the oracle side when you call DBMS_DEBUG_JDWP.connect_tcp() ? Do you have an error?

**Comment by mickeypearce** [comment] 2020-04-02 09:01
No, it actually connected. 
I was missing this step, so this is the right way to connect from the DB to debugger?
And run procedure, etc inside this connected sesssion?

**Comment by zerabba** [comment] 2020-04-02 10:50
Yes, because in vscode we just connect on an existing oracle session through JDWP. Once the connection is established, you can call package and it will stop where you put a breakpoint.

In our company, we use vscode to edit plsql files. We use the extension plsql-language to build the package and start the debug with this extension. Then, we launch our client application (in delphi) and in this app we have a shortcut that call the method DBMS_DEBUG_JDWP.connect_tcp(). In that way, we can directly debug plsql code in our application context.

**Comment by zerabba** [comment] 2020-04-02 10:50
Can I close the issue?

**Closed as completed** 2020-04-02 10:56 UTC

**Comment by mickeypearce** [comment] 2020-04-03 07:46
@zerabba , one more thing :)

I added "Connect" and "Disconnect" to my app, it succesfully connects, but I cannot get it to stop on a breakpoint. Is there someting else I am missing.

It is a problem if app connects with a different user than actual schema of objects? I added both to "watchingSchemas".

Thanks again for your help.

**Comment by zerabba** [comment] 2020-04-03 07:56
Did you GRANT DEBUG ANY PROCEDURE TO <the user connected>?

**Comment by mickeypearce** [comment] 2020-04-03 08:51
Yes.

**Comment by zerabba** [comment] 2020-04-04 06:46
In my app it was not stopping first, because i was missing this grant on the user connected.

Can you maybe try with sql developper and see if it stopps (right click on your schema and choose remote debug)? If it is working, then the problem is in my extension... In that case, if you can provide more informations, I will try to find the problem :)

**Comment by mickeypearce** [comment] 2020-04-04 19:25
It works from SQL Developer, it stopped on breakpoint, surprisingly..

I tried changing my package "headers" in VSCode `.sql` file to:
`create or replace PACKAGE BODY        "PCK_1"`
as this is how they are stored on DB..

Originally my VS Code file included also schema:
`CREATE OR REPLACE PACKAGE BODY "SCHEMA1"."PCK_1" `
but this change didn't make any difference...

Package source is the same, breakpoint is on the same line as in SQL Developer....

I also noticed that "LOADED SCRIPTS" appears aftear clients connects, but it remains empty if that is a problem...

I am on Windows 10 btw...

Is there anything I could check?

**Comment by zerabba** [comment] 2020-04-05 06:48
Now I see the problem, I didn't thought about the double quote when I wrote the regex that parse the source file. 

In your case, you don't need the double quote in your source file if your package name is in uppercase. If you remove it, you should have the breakpoint. Maybe you can try that way for the moment?

But I know that package can be between double quote to be stored with case sensivity. For that, I need to check how I need to call the breakpoint and adapt my extension...

**Comment by mickeypearce** [comment] 2020-04-05 08:47
OK, I will try and let you know.

Maybe even adapting regex to read "schema" prepending package name wouldn't be a bad idea.

**Comment by zerabba** [comment] 2020-04-05 11:23
I've made a new version that should fix your problem with the double quote...

If you can test it and let me know if it's working on your side?

Thanks!

**Comment by mickeypearce** [comment] 2020-04-05 14:47
It works! Quite impressed. 👍

**Comment by zerabba** [comment] 2020-04-05 15:05
Thanks for the feedback :)

There is also a new possibility to evaluate values if you take a look at
the readme. Maybe it will be usefull when debugging to have more
informations (sys_context, values in temporary tables,...).

And if you want to help to extend this extension or make it better, i will
be happy if other people contribute to it :)

Le dim. 5 avr. 2020 à 16:48, Mickey Pearce <notifications@github.com> a
écrit :
